dist: xenial   # required for Python >= 3.7
language: python
python: 3.7

cache:
  pip: true
  directories:
    - ouoou
    #- svnRepos
    #- gitRepos

script:
  - python ouoouDownload.py $OUOOU_DADAO_ID $OUOOU_DADAO_START
  #- python sync.py

deploy:
  provider: pages
  local_dir: ouoou
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
